# First line
image: python:latest
services:
  - docker:dind

stages:
  - test

# this is a job called step-test, the runs whatever is in script
step-test:
  stage: test
  before_script:
    - pip install docker-compose
  script:
    - docker-compose run app sh -c "python manage.py test && flake8"
