# First line
services:
  - docker

before_script:
  - pip install docker-compose

# this is a job called test, the runs whatever is in script
test:
  script:
    - docker-compose run app sh -c "python manage.py test && flake8"
