image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - test
  
before_script:
  - apk update
  - apk add py3-pip build-base
  - pip install docker-compose

# this is a job called step-test, the runs whatever is in script
step-test:
  stage: test
  script:
    - docker-compose run app sh -c "python manage.py test && flake8"
